services:
  auth-service:
    build:
      context: .
      dockerfile: docker/auth.Dockerfile
    volumes:
      - ./backend/auth-service:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=auth-db
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      auth-db:
        condition: service_healthy

  board-service:
    build:
      context: .
      dockerfile: docker/board.Dockerfile
    volumes:
      - ./backend/board-service:/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=board-db
      - DB_NAME=board_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      board-db:
        condition: service_healthy

  realtime-service:
    build:
      context: .
      dockerfile: docker/realtime.Dockerfile
    volumes:
      - ./backend/realtime-service:/app
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=realtime-db
      - DB_NAME=realtime_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
      realtime-db:
        condition: service_healthy

  auth-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5

  board-db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: board_db
    volumes:
      - board_pgdata:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5

  realtime-db:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtime_db
    volumes:
      - realtime_pgdata:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth_pgdata:
  board_pgdata:
  realtime_pgdata:
